export const DEFAULT_MENTORS = [
  {
    id: "mentor-1",
    _id: "mentor-1",
    name: "Ananya Iyer",
    title: "Principal Engineer",
    company: "series-C fintech",
    industry: "Fintech",
    specialty: "Distributed Systems",
    experienceYears: 12,
    location: "Bengaluru",
    bio: "Built payment rails that move money for 40 million users. I mentor engineers who want to go deep on system design without losing sight of the business.",
    expertise: [
      "System Design",
      "Distributed Systems",
      "AWS",
      "Kubernetes",
      "Mentoring",
    ],
    languages: ["English", "Tamil", "Hindi"],
    rating: 4.9,
    menteeCount: 27,
    avatarColor: "#ffb340",
  },
  {
    id: "mentor-2",
    _id: "mentor-2",
    name: "Rohan Mehta",
    title: "Director of Engineering",
    company: "growth-stage SaaS",
    industry: "SaaS",
    specialty: "Engineering Management",
    experienceYears: 15,
    location: "Pune",
    bio: "Went from IC to managing 45 engineers across five teams. I help technical people figure out whether the management track is actually right for them.",
    expertise: [
      "Leadership",
      "Hiring",
      "Stakeholder Management",
      "OKRs",
      "Strategy",
    ],
    languages: ["English", "Hindi", "Marathi"],
    rating: 4.8,
    menteeCount: 41,
    avatarColor: "#3ddc97",
  },
  {
    id: "mentor-3",
    _id: "mentor-3",
    name: "Sara Cherian",
    title: "Staff Data Scientist",
    company: "AI-first healthtech",
    industry: "Healthtech",
    specialty: "Applied Machine Learning",
    experienceYears: 9,
    location: "Bengaluru",
    bio: "Productionised ML models for diagnostic imaging. I work with people pivoting into data science who need a realistic map of what the first two years look like.",
    expertise: ["Machine Learning", "Python", "PyTorch", "Statistics", "MLOps"],
    languages: ["English", "Malayalam"],
    rating: 4.9,
    menteeCount: 33,
    avatarColor: "#5dade2",
  },
  {
    id: "mentor-4",
    _id: "mentor-4",
    name: "Dev Patel",
    title: "Senior Product Manager",
    company: "product-led marketplace",
    industry: "Product",
    specialty: "Product Strategy",
    experienceYears: 8,
    location: "Mumbai",
    bio: "Shipped products used by 12 million people. I mentor engineers curious about the PM track and PMs trying to move from feature factory to outcomes.",
    expertise: [
      "Product Strategy",
      "User Research",
      "A/B Testing",
      "Stakeholder Management",
    ],
    languages: ["English", "Hindi", "Gujarati"],
    rating: 4.7,
    menteeCount: 22,
    avatarColor: "#e74c8b",
  },
  {
    id: "mentor-5",
    _id: "mentor-5",
    name: "Meera Krishnan",
    title: "Engineering Manager",
    company: "Series B logistics startup",
    industry: "Logistics",
    specialty: "Career Transitions",
    experienceYears: 11,
    location: "Hyderabad",
    bio: "Pivoted from QA to SRE to engineering management. I specialise in helping people navigate adjacent-field moves without starting from zero.",
    expertise: ["Career Pivots", "SRE", "Leadership", "Communication"],
    languages: ["English", "Telugu", "Tamil"],
    rating: 4.8,
    menteeCount: 35,
    avatarColor: "#9b7ed4",
  },
  {
    id: "mentor-6",
    _id: "mentor-6",
    name: "Arjun Nair",
    title: "Staff Frontend Engineer",
    company: "design-led consumer app",
    industry: "Consumer Tech",
    specialty: "Frontend Architecture",
    experienceYears: 10,
    location: "Bengaluru",
    bio: "Care about performance and accessibility the way most people care about features. I mentor frontend engineers who want to reach staff level through craft.",
    expertise: [
      "React",
      "TypeScript",
      "Performance",
      "Accessibility",
      "System Design",
    ],
    languages: ["English", "Malayalam", "Hindi"],
    rating: 4.7,
    menteeCount: 19,
    avatarColor: "#f4845f",
  },
  {
    id: "mentor-7",
    _id: "mentor-7",
    name: "Priya Saxena",
    title: "Head of Data",
    company: "mid-size e-commerce",
    industry: "E-commerce",
    specialty: "Data Leadership",
    experienceYears: 13,
    location: "Gurugram",
    bio: "Built the analytics function from one analyst to a team of eighteen. I help data professionals decide between going deeper technically versus leading a team.",
    expertise: ["Data Strategy", "Leadership", "SQL", "Statistics", "Hiring"],
    languages: ["English", "Hindi"],
    rating: 4.9,
    menteeCount: 28,
    avatarColor: "#5ab1bb",
  },
  {
    id: "mentor-8",
    _id: "mentor-8",
    name: "Kabir Anand",
    title: "Senior SRE",
    company: "global cloud provider",
    industry: "Cloud Infrastructure",
    specialty: "Reliability Engineering",
    experienceYears: 7,
    location: "Remote",
    bio: "On-call for systems that cannot go down. I mentor engineers moving into SRE who want to understand reliability as a product, not a checkbox.",
    expertise: [
      "SRE",
      "Kubernetes",
      "Observability",
      "Go",
      "Incident Response",
    ],
    languages: ["English", "Hindi", "Punjabi"],
    rating: 4.6,
    menteeCount: 15,
    avatarColor: "#d4a017",
  },
];

export const DEFAULT_INDUSTRIES = [
  ...new Set(DEFAULT_MENTORS.map((m) => m.industry)),
].sort();

export const DEFAULT_SPECIALTIES = [
  ...new Set(DEFAULT_MENTORS.map((m) => m.specialty)),
].sort();

export const DEMO_ACCOUNTS = {
  student: {
    id: "demo-student-user",
    _id: "demo-student-user",
    name: "Ishaan Verma",
    email: "ishaan.verma@demo.careerpath.app",
    role: "student",
    headline: "MCA final-year student exploring software and data paths",
    avatarColor: "#ffb340",
  },
  mentor: {
    id: "demo-mentor-user",
    _id: "demo-mentor-user",
    name: "Ananya Iyer",
    email: "ananya.iyer@demo.careerpath.app",
    role: "mentor",
    headline: "Principal Engineer at series-C fintech",
    avatarColor: "#ffb340",
  },
  admin: {
    id: "demo-admin-user",
    _id: "demo-admin-user",
    name: "Faculty Reviewer",
    email: "admin@careerpath.app",
    role: "admin",
    headline: "Project evaluation account",
    avatarColor: "#3ddc97",
  },
  guest: {
    id: "offline-guest-user",
    _id: "offline-guest-user",
    name: "Offline Explorer",
    email: "explorer@careerpath.offline",
    role: "student",
    headline: "Exploring career paths in offline mode",
    avatarColor: "#3ddc97",
  },
};

export const DEMO_STUDENT_PROFILE = {
  id: "demo-student-profile",
  _id: "demo-student-profile",
  userId: "demo-student-user",
  educationLevel: "Postgraduate",
  educationField: "Computer Applications",
  graduationYear: 2026,
  currentRole: "Intern — Backend Developer",
  experienceYears: 0.5,
  location: "Pune",
  targetRole: "Senior Engineer or Data Scientist",
  currency: "INR",
  skills: [
    { name: "JavaScript", proficiency: 3 },
    { name: "React", proficiency: 2 },
    { name: "Node.js", proficiency: 3 },
    { name: "Python", proficiency: 3 },
    { name: "SQL", proficiency: 4 },
    { name: "Communication", proficiency: 3 },
  ],
  interests: ["coding", "data", "problem solving", "systems"],
  constraints: {
    upskillingBudget: 15000,
    timeAvailability: "15 hours/week",
    locationFlexibility: "open to relocate",
  },
};
